import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Activity,
  Bell,
  LineChart,
  ShieldCheck,
  Sparkles,
  Stethoscope,
  Users,
  Zap,
} from "lucide-react";

const features = [
  {
    title: "Triage at a glance",
    description: "Red, amber, green queues highlight who needs action now.",
    icon: AlertIcon,
  },
  {
    title: "Wearable trend intelligence",
    description: "14-day baselines and deltas expose subtle decline early.",
    icon: LineChart,
  },
  {
    title: "Clinician-ready summaries",
    description: "SBAR summaries and alerts keep handoffs consistent.",
    icon: Stethoscope,
  },
  {
    title: "Live alerting",
    description: "Escalations notify teams fast with clear next steps.",
    icon: Bell,
  },
  {
    title: "Patient engagement",
    description: "Conversational check-ins boost adherence and trust.",
    icon: Users,
  },
  {
    title: "Secure by design",
    description: "Designed for clinical workflows and compliance.",
    icon: ShieldCheck,
  },
];

function AlertIcon({ className }: { className?: string }) {
  return <Activity className={className} />;
}

export default function Landing() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 border-b bg-card/80 backdrop-blur-md">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground">
              <Activity size={20} />
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">CardioWatch</p>
              <p className="text-xs text-muted-foreground">Signal Guide Health</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" onClick={() => navigate("/dashboard")}>
              Open Dashboard
            </Button>
            <Button onClick={() => navigate("/demo")}>View Demo</Button>
          </div>
        </div>
      </header>

      <main>
        <section className="relative overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-background via-accent/40 to-secondary/50" />
          <div className="absolute -top-20 right-0 h-72 w-72 rounded-full bg-primary/10 blur-3xl" />
          <div className="absolute bottom-0 left-0 h-72 w-72 rounded-full bg-triage-green/10 blur-3xl" />

          <div className="container relative mx-auto grid gap-10 px-4 py-16 lg:grid-cols-[1.1fr_0.9fr] lg:py-24">
            <div className="space-y-6">
              <Badge className="w-fit bg-primary/10 text-primary">Investor-ready demo</Badge>
              <h1 className="text-4xl font-semibold tracking-tight text-foreground md:text-5xl">
                CardioWatch turns post-discharge risk into actionable care.
              </h1>
              <p className="text-base text-muted-foreground md:text-lg">
                A clinician-first dashboard that fuses wearable signals, patient check-ins,
                and triage automation to reduce readmissions and scale cardiac follow-up.
              </p>
              <p className="text-sm text-muted-foreground">
                Demo generated by Recep Adiyaman for investor presentations.
              </p>
              <div className="flex flex-wrap gap-3">
                <Button size="lg" onClick={() => navigate("/demo")}>
                  Launch patient demo
                </Button>
                <Button size="lg" variant="outline" onClick={() => navigate("/dashboard")}>
                  Explore clinician view
                </Button>
              </div>
              <div className="flex flex-wrap gap-6 text-sm text-muted-foreground">
                <span className="flex items-center gap-2">
                  <Zap size={16} className="text-primary" />
                  Faster escalations
                </span>
                <span className="flex items-center gap-2">
                  <Sparkles size={16} className="text-primary" />
                  Automated summaries
                </span>
                <span className="flex items-center gap-2">
                  <ShieldCheck size={16} className="text-primary" />
                  Clinical-grade UX
                </span>
              </div>
            </div>

            <div className="space-y-4">
              <Card className="border bg-card/90 p-6 shadow-lg">
                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  Snapshot
                </p>
                <div className="mt-4 grid grid-cols-2 gap-4">
                  <Card className="p-4">
                    <p className="text-xs text-muted-foreground">Active alerts</p>
                    <p className="text-2xl font-semibold text-triage-red">2</p>
                  </Card>
                  <Card className="p-4">
                    <p className="text-xs text-muted-foreground">Patients monitored</p>
                    <p className="text-2xl font-semibold text-foreground">128</p>
                  </Card>
                  <Card className="p-4">
                    <p className="text-xs text-muted-foreground">Avg. response time</p>
                    <p className="text-2xl font-semibold text-foreground">12m</p>
                  </Card>
                  <Card className="p-4">
                    <p className="text-xs text-muted-foreground">Readmission risk</p>
                    <p className="text-2xl font-semibold text-triage-amber">-18%</p>
                  </Card>
                </div>
              </Card>
              <Card className="border bg-card/90 p-5">
                <div className="flex items-start gap-3">
                  <div className="rounded-lg bg-triage-green-bg p-2">
                    <Activity className="text-triage-green" size={18} />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-foreground">Signal integrity</p>
                    <p className="text-xs text-muted-foreground">
                      Trend baselines keep clinicians confident in the next action.
                    </p>
                  </div>
                </div>
              </Card>
            </div>
          </div>
        </section>

        <section className="container mx-auto px-4 py-16">
          <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
            <div>
              <h2 className="text-3xl font-semibold text-foreground">Platform features</h2>
              <p className="text-sm text-muted-foreground">
                Built for clinical clarity, operational scale, and investor-ready storytelling.
              </p>
            </div>
            <Button variant="outline" onClick={() => navigate("/demo")}>
              See the flow
            </Button>
          </div>
          <div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {features.map((feature) => {
              const Icon = feature.icon;
              return (
                <Card key={feature.title} className="p-5">
                  <div className="flex items-start gap-3">
                    <div className="rounded-lg bg-primary/10 p-2">
                      <Icon className="text-primary" size={18} />
                    </div>
                    <div>
                      <p className="text-sm font-semibold text-foreground">{feature.title}</p>
                      <p className="text-xs text-muted-foreground">{feature.description}</p>
                    </div>
                  </div>
                </Card>
              );
            })}
          </div>
        </section>

        <section className="container mx-auto px-4 pb-16">
          <div className="grid gap-6 rounded-3xl bg-secondary/60 p-8 lg:grid-cols-2">
            <div className="space-y-3">
              <h3 className="text-2xl font-semibold text-foreground">Why investors care</h3>
              <p className="text-sm text-muted-foreground">
                CardioWatch targets a high-cost, high-volume segment with clear ROI.
              </p>
              <div className="space-y-2 text-sm text-foreground">
                <p>• Readmission prevention lowers penalties and improves margins.</p>
                <p>• Nurse workload scales with smart triage, not headcount.</p>
                <p>• Wearable data unlocks continuous post-discharge engagement.</p>
              </div>
            </div>
            <div className="space-y-3">
              <h3 className="text-2xl font-semibold text-foreground">Go-to-market ready</h3>
              <p className="text-sm text-muted-foreground">
                Demo-ready workflows let stakeholders experience the patient and clinician journey.
              </p>
              <div className="grid gap-3 sm:grid-cols-2">
                <Card className="p-4">
                  <p className="text-xs text-muted-foreground">Target customers</p>
                  <p className="text-sm font-semibold text-foreground">Hospital systems</p>
                </Card>
                <Card className="p-4">
                  <p className="text-xs text-muted-foreground">Revenue model</p>
                  <p className="text-sm font-semibold text-foreground">SaaS + per-patient</p>
                </Card>
                <Card className="p-4">
                  <p className="text-xs text-muted-foreground">Data sources</p>
                  <p className="text-sm font-semibold text-foreground">Wearables + RPM</p>
                </Card>
                <Card className="p-4">
                  <p className="text-xs text-muted-foreground">Clinical impact</p>
                  <p className="text-sm font-semibold text-foreground">Faster escalations</p>
                </Card>
              </div>
            </div>
          </div>
        </section>

        <section className="container mx-auto px-4 pb-16">
          <div className="grid gap-4 lg:grid-cols-2">
            <Card className="p-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Customer demo
              </p>
              <h3 className="mt-2 text-xl font-semibold text-foreground">
                Patient experience
              </h3>
              <p className="mt-2 text-sm text-muted-foreground">
                Walk through the daily check-in and escalation flow.
              </p>
              <Button asChild className="mt-4">
                <Link to="/demo">Open patient demo</Link>
              </Button>
            </Card>
            <Card className="p-6">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Doctor demo
              </p>
              <h3 className="mt-2 text-xl font-semibold text-foreground">
                Clinician dashboard
              </h3>
              <p className="mt-2 text-sm text-muted-foreground">
                Review triage, alerts, SBAR summaries, and vitals.
              </p>
              <Button asChild variant="outline" className="mt-4">
                <Link to="/dashboard">Open clinician view</Link>
              </Button>
            </Card>
          </div>
        </section>

        <section className="container mx-auto px-4 pb-20">
          <Card className="flex flex-col items-start gap-4 border bg-card/90 p-8 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <h3 className="text-2xl font-semibold text-foreground">
                Ready for an investor walkthrough?
              </h3>
              <p className="text-sm text-muted-foreground">
                Run the patient demo and clinician dashboard in under 3 minutes.
              </p>
            </div>
            <div className="flex flex-wrap gap-3">
              <Button size="lg" onClick={() => navigate("/demo")}>
                Launch demo
              </Button>
              <Button size="lg" variant="outline" onClick={() => navigate("/dashboard")}>
                Open dashboard
              </Button>
            </div>
          </Card>
        </section>
      </main>

      <footer className="border-t bg-card/60">
        <div className="container mx-auto flex flex-col gap-2 px-4 py-6 text-xs text-muted-foreground md:flex-row md:items-center md:justify-between">
          <span>Copyright (c) 2026 Recep Adiyaman. All rights reserved.</span>
          <span>CardioWatch demo landing page (home) with patient and clinician demos.</span>
        </div>
      </footer>
    </div>
  );
}
